import fs from 'node:fs/promises';
import path from 'node:path';
import { Presentation, PresentationFile } from '@oai/artifact-tool';
import { resolvePresentationFont, applyPresentationChartFont, finalizePresentation } from '/Users/joey/.codex/plugins/cache/openai-primary-runtime/presentations/26.903.11726/skills/presentations/container_tools/artifact_tool_utils.mjs';
const ROOT='/Users/joey/research/miles/report/soutenance';
const SKILL='/Users/joey/.codex/plugins/cache/openai-primary-runtime/presentations/26.903.11726/skills/presentations';
const PY='/Users/joey/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3';
const C={bg:'#FFFFFF',ink:'#142E38',muted:'#577079',teal:'#007F7B',amber:'#C97433',pale:'#E4F1EE',sand:'#F6E9DC',line:'#CBD6D6',white:'#FFFFFF',dark:'#102C36'};
const font=resolvePresentationFont();
console.log('Font:',font);
const assets=Object.fromEntries(await Promise.all((await fs.readdir(path.join(ROOT,'.build','math'))).filter(n=>n.endsWith('.png')).map(async n=>[n.slice(0,-4),await fs.readFile(path.join(ROOT,'.build','math',n))])));
const p=Presentation.create({slideSize:{width:1280,height:720}});
let index=0; const script=[]; const chartOwners=[],tableOwners=[];
function box(s,x,y,w,h,fill,line='none',geo='rect'){return s.shapes.add({geometry:geo,position:{left:x,top:y,width:w,height:h},fill,line:{fill:line,width:line==='none'?0:1}})}
function text(s,str,x,y,w,h=60,size=28,color=C.ink,bold=false,align='left'){let z=box(s,x,y,w,h,'none');z.text=str;z.text.style={typeface:font,fontSize:size,color,bold,alignment:align,autoFit:'none',verticalAlignment:'middle'};return z;}
function equation(s,name,x,y,w,h,alt=name){s.images.add({blob:assets[name],contentType:'image/png',alt,fit:'contain',position:{left:x,top:y,width:w,height:h}});}
function rule(s,x,y,w,color=C.line){box(s,x,y,w,2,color)}
function slide(title,section,seconds,notes,source,dark=false){let s=p.slides.add();index++;s.background.fill=dark?C.dark:C.bg; if(title)text(s,title,64,65,1152,102,43,dark?C.white:C.ink,true); text(s,section,66,27,1050,24,15,dark?'#82BCBC':C.teal,true);text(s,String(index).padStart(2,'0'),1160,665,55,25,16,dark?'#9CB4BB':C.muted,false,'right');rule(s,64,651,1152,dark?'#31505A':C.line); const n=`${seconds?`Target: ${seconds} seconds.\n\n`: 'Backup slide. Use only during questions.\n\n'}${notes}\n\nSource: ${source}`;s.speakerNotes.textFrame.setText(n);script.push({index,title,section,seconds,notes,source});return s;}
function note(s,str){text(s,str,64,603,1138,39,19,C.muted);}
function callout(s,str,y=535,color=C.teal){rule(s,64,y,60,color);text(s,str,145,y-13,1040,63,29,color,true);}
function label(s,str,x,y,w=350,color=C.teal){text(s,str,x,y,w,35,22,color,true);}
function block(s,str,x,y,w,h,fill=C.pale){box(s,x,y,w,h,fill);text(s,str,x+15,y+8,w-30,h-16,27,C.ink,true,'center');}
function join(s,x,y,w,color=C.muted){box(s,x,y,w,3,color);box(s,x+w-10,y-6,16,16,color,'none','chevron');}
function chart(s,cats,series,{x=64,y=195,w=1152,h=365,max=1.3,format='0.0',legend=true,type='bar',title}={}){const sty={typeface:font,fontSize:20,fill:C.muted};const ch=s.charts.add(type,{position:{left:x,top:y,width:w,height:h},categories:cats,series:series.map((v,i)=>({name:v.name,values:v.values,fill:v.color??[C.teal,C.amber][i%2],line:{fill:v.color??[C.teal,C.amber][i%2],width:type==='line'?3:0},valuesFormatCode:format,marker:{symbol:type==='line'?'circle':'none',size:7}})),hasLegend:legend,legend:{position:'bottom',overlay:false,textStyle:sty},barOptions:{direction:'column',grouping:'clustered',gapWidth:95},xAxis:{textStyle:sty,line:{fill:C.line,width:1},majorGridlines:null},yAxis:{title:({'Retained task gain':'Retained task gain','Own-objective detector AUC':'Detector AUC','Final-answer accuracy':'Final-answer accuracy','Regret at horizon 32':'Regret','Held-out boundary AUC':'Boundary AUC'})[series[0].name],min:0,max,numberFormatCode:format,textStyle:sty,majorGridlines:{fill:C.line,width:1}},dataLabels:{showValue:type==='bar',position:'outEnd',textStyle:{...sty,fill:C.ink,fontSize:21}},chartFill:C.bg,plotAreaFill:C.bg});applyPresentationChartFont(ch,{fontFamily:font});chartOwners.push(index);return ch;}
function table(s,values,x,y,w,h,widths){const t=s.tables.add({rows:values.length,columns:values[0].length,left:x,top:y,width:w,height:h,values,columnWidths:widths});for(let i=0;i<values.length;i++)for(let j=0;j<values[i].length;j++){const cell=t.getCell(i,j);cell.fill=i===0?C.ink:i%2?C.white:C.pale;cell.text.style={typeface:font,fontSize:22,color:i===0?C.white:C.ink,bold:i===0};}tableOwners.push(index);return t;}
let s;
s=slide('', 'MASTER’S THESIS · IASD · PSL · 2026',25,`My internship at MILES, LAMSADE, asks how much information a language model needs to acquire or preserve for a behavior to survive. I studied this in two settings: small parameter updates during fine-tuning, and intermediate states during reasoning. I will first set up the LLM-specific objects, then present the strongest evidence and what it leaves open.`, 'Report title page and §1.1.',true);
text(s,'Information constraints',64,140,1100,90,65,C.white,true);text(s,'in fine-tuning and\nreasoning language models',64,235,1120,170,57,C.white,true);rule(s,64,453,110,C.teal);text(s,'Joey David',64,490,600,45,32,C.white,true);text(s,'MILES, LAMSADE · Université Paris Dauphine–PSL',64,542,1100,35,24,'#B5CBD0');text(s,'Supervision: Paul Caillon and Alexandre Allauzen',64,583,1100,34,22,'#B5CBD0');
s=slide('How much information must survive?', 'RESEARCH QUESTION',30,`There are two concrete objects here. At training time I keep the base model shared and fixed, and ask how small a saved update can be while preserving its effect. At inference time I ask what state must remain available so the next computation can still work. These are different experiments, with different units. The shared question concerns usefulness relative to a receiver and a specified behavior. I do not claim a common predictive law.`, 'Report §1.2, §5.2–5.3.');
label(s,'Fine-tuning',64,205);text(s,'A compressed update',64,258,530,55,37,C.ink,true);text(s,'What must a fixed model receive\nto retain a learned behavior?',64,329,525,100,30);box(s,620,205,2,240,C.line);label(s,'Reasoning',700,205,350,C.amber);text(s,'An intermediate state',700,258,510,55,37,C.ink,true);text(s,'What must the next computation\nreceive to continue correctly?',700,329,510,100,30);callout(s,'Receiver, task, and update rule define what is useful.');
s=slide('Autoregressive language models', 'FOUNDATIONS · LANGUAGE MODELS',50,`A language model is a conditional density model over token sequences. The training objective is the same maximum-likelihood principle familiar from statistical learning, applied to next-token prediction. A transformer turns the available prefix into hidden vectors and a softmax distribution. Generation appends a sampled or selected token, then repeats. A token is a piece of text, not necessarily a word. This gives us both a visible token sequence and hidden activations at each position and layer. Those are the objects we later compress or probe.`, 'Report §2.1.');
equation(s,'autoregressive',64,184,1050,104,'Autoregressive factorization over tokens');block(s,'Prefix tokens',64,350,275,100);join(s,350,399,70);block(s,'Transformer',435,350,345,100);join(s,794,399,70);block(s,'Next-token distribution',880,350,335,100);text(s,'Hidden vectors hₜ at each layer',440,466,430,45,24,C.muted);callout(s,'Training minimizes next-token negative log-likelihood.');note(s,'At generation time, each new token extends the prefix.');
s=slide('LoRA and QLoRA', 'FOUNDATIONS · LOW-RANK ADAPTATION',70,`Full fine-tuning adjusts a large number of weights. LoRA restricts each selected matrix update to a low-rank factorization BA. We freeze W and train the smaller factors A and B. For a square d by d matrix, this changes the number of trainable values from d squared to 2dr. QLoRA also stores the frozen backbone in four-bit form, while training adapters in higher precision. The four-bit backbone is a training-memory choice. In my experiments I subsequently compress the trained adapter itself. Rank controls a parameterization dimension; the saved numbers still need a numerical code. It is therefore not itself a bit count.`, 'Report §2.3–2.4. Hu et al., LoRA (2022). Dettmers et al., QLoRA (2023), bibliography entries hu2022lora and dettmers2023qlora.');
equation(s,'lora',64,185,1152,92,'Low-rank update and dimensions of A and B');block(s,'Frozen W\n4-bit backbone in QLoRA',64,325,560,140,C.pale);block(s,'Trainable A and B\nHigher-precision adapter',664,325,552,140,C.sand);equation(s,'lora_count',210,478,860,67,'Trainable value count P equals r times the sum of matrix dimensions');callout(s,'This work compresses the adapter after training.',559);note(s,'Count shown for one adapted matrix. Sum over modules for the full adapter.');
s=slide('The adapter’s numerical code determines its rate', 'FOUNDATIONS · LORA COMPRESSION',55,`The low-rank factorization reduces the number of values we need to store. Here P denotes the total count across adapted matrices. It does not specify how many bits each value needs. For a uniform b-bit quantizer, the packed payload contains bP bits, plus scales and metadata. The hats denote the dequantized factors the receiver actually uses. Our implementation then applies zlib to the complete payload. Repeated codes and compressible structure can reduce the resulting file size. We measure that size directly and reload it. The reconstruction of BA can differ from the original, so the decisive question is what happens to the model’s output. Nothing here claims that low rank alone guarantees a particular behavioral compression rate.`, 'Report §2.3–2.5, §3.3 and Appendix Codec ladder. The fixed-width storage equation is direct parameter accounting.');
equation(s,'quantized',64,191,1152,97,'Reconstructed LoRA update and fixed-width bit count');
label(s,'Before entropy coding',64,332);text(s,'b bits per value, plus the information\nneeded to decode the numbers',64,383,548,105,29);label(s,'After packing and zlib',700,332);text(s,'The actual file length determines R.\nThe original value count P stays fixed.',700,383,516,105,29);equation(s,'rate',64,510,1152,76,'Exact serialized rate in bits per original adapter value');note(s,'Backbone weights remain shared. This rate counts only the complete adapter file.');
s=slide('Coding and rate–distortion', 'FOUNDATIONS · INFORMATION THEORY',60,`Shannon coding relates probability to description length: an event of probability p takes minus log base two p bits in an ideal code. Entropy averages that quantity. Negative log likelihood therefore has a coding interpretation, but an ideal code length is not automatically the size of a file. Rate–distortion asks for a short representation under a specified error tolerance. The choice of distortion is essential. Here, both sides already have the base model, and I only count the additional adapter file. This is an operational compression experiment over a restricted codec family, not an estimate of an intrinsic Shannon rate–distortion function or a universal lower bound.`, 'Report §2.5 and §3.3. Cover and Thomas, Elements of Information Theory (2006).');
equation(s,'entropy',64,199,1135,90,'Ideal code length and entropy as expected code length');label(s,'Lossy coding',64,339);text(s,'Minimize the message length\nunder an error constraint.',64,390,535,100,32,C.amber,true);label(s,'Side information',700,339);text(s,'Both sides already have the base model.\nOnly the update enters the file budget.',700,390,510,111,29);callout(s,'The distortion measure specifies the behavior to preserve.');
s=slide('A chain of thought for April and May sales', 'FOUNDATIONS · COT EXAMPLE',55,`Consider the example from the report: Natalia sold 48 clips in April, then half as many in May. The goal is the total. The graph separates facts read from the prompt from derived claims. The first calculation gives May as 24. The final calculation combines that with April to get 72. A written chain of thought can spell out these intermediate claims before the answer. This graph describes an idealized dependency structure. It is the hypothesis that motivated my trajectory work, not an observed circuit inside the model. The next slide shows how an autoregressive model actually generates the text that expresses such a computation.`, 'Report §4.2, Figure 8, Idealized solution object as a DAG. Original TikZ graph reused from tex/04_reasoning_trajectories.tex.');
text(s,'April: 48 clips\nMay: half as many\n\nTotal over both months?',64,232,322,234,31,C.ink,true);equation(s,'solution_graph',390,192,830,382,'Report Figure 8: n_Apr=48, n_May=n_Apr/2=24, total=n_Apr+n_May=72');callout(s,'Intermediate claims make the computation explicit.',568,C.amber);note(s,'The report’s hypothetical solution graph. Its nodes need not coincide with token or hidden-state boundaries.');
s=slide('How the model builds a chain of thought', 'FOUNDATIONS · AUTOREGRESSIVE COMPUTATION',65,`Let x be the problem, z the intermediate trace, and y the final answer. The joint probability factorizes into next-token probabilities for the trace and the probability of the answer given that trace. Generation samples, or greedily selects, a token and appends it to the context. Each added token gives the transformer another forward pass. The semantic node n May equals 24 can require several tokens, so semantic steps and token steps differ. Training on demonstrations maximizes this joint likelihood. With final-answer rewards, a reinforcement learning objective instead weights generated traces by their outcomes. Conceptually we can marginalize over traces, but standard generation samples a path rather than evaluating that sum. The displayed answer distribution is the distribution induced by this CoT procedure.`, 'Report §2.1–2.2 and §4.1. Joint factorization and marginalization follow the probability chain rule.');
equation(s,'cot_joint',64,191,1152,112,'Joint probability of the reasoning trace and answer');text(s,'x: problem     z: intermediate trace     y: final answer',64,304,1152,32,23,C.muted);label(s,'Generate a token, then extend the context',64,340,1120,C.amber);equation(s,'cot_generate',64,392,1152,74,'Sample a next reasoning token and append it to the prefix');text(s,'Each token adds a transformer pass.\nOne semantic step can span many tokens.',64,507,610,97,28);equation(s,'cot_marginal',736,504,460,66,'CoT answer distribution marginalizes over possible traces');text(s,'Generation samples a path through this sum.',726,579,490,41,20,C.muted);
s=slide('An exact rate for a fixed learned update', 'I · FINE-TUNING',85,`I train a rank-16 adapter once and hold the checkpoint fixed. I then compress it, write a complete file including scales and metadata, reload that file into the frozen backbone, and measure held-out behavior. Every point changes the representation of the same update, rather than training a new model. Rate is file size in bits divided by the number of original adapter values. Retention normalizes the gain over the frozen baseline by the gain of the raw adapter. The operational threshold is the smallest measured rate reaching 90 percent retention. It depends on the codec ladder, adapter architecture, model, and scored behavior. If the raw gain is tiny or nonpositive this ratio needs separate care.`, 'Report §3.3 and Appendix, Codec ladder.');
block(s,'Fixed adapter',64,201,250,72);join(s,325,237,52);block(s,'Encode file',392,201,250,72);join(s,654,237,50);block(s,'Reload',718,201,202,72);join(s,932,237,50);block(s,'Evaluate',996,201,220,72);equation(s,'retention',260,309,760,98,'Gain retained after compression relative to the raw adapter');equation(s,'constraint',64,448,1152,93,'Minimum measured rate over the codec family subject to 90 percent retained utility');note(s,'C: tested codecs     M: frozen model     U: scored behavior     L: held-out loss');
s=slide('Weight error misses behavioral damage', 'I · A FAILED ALLOCATION RULE',55,`The first allocator spent bits to minimize weight reconstruction error. It could choose a different precision for each row or drop a row. The simple uniform sign code did much better at roughly one bit per adapter value. This figure uses retained GSM8K exact-match gain, so it is a task-accuracy example, distinct from the likelihood-based threshold used in most later results. The original figure shows comparable reconstruction error despite an 83-point retention gap. That counterexample rejects global weight RMSE as a sufficient behavioral distortion. It does not say every adaptive allocator must fail.`, 'Report §3.4 and media/fineqcomp/plots/mdl_vs_uniform.png. Values 85.7% and 2.6% are labels in the report figure.');
chart(s,['Uniform sign code','Adaptive allocation'],[{name:'Retained task gain',values:[.857,.026],color:C.teal}],{x:64,y:209,w:705,h:330,max:1,format:'0.0%',legend:false});text(s,'≈ 1 bit / value',850,224,345,55,36,C.teal,true);text(s,'Similar weight RMSE\n83 points apart in\nretained task gain',850,315,350,150,32);callout(s,'Behavior must be measured at the model’s output.');note(s,'Mistral-7B + rank-16 LoRA, MetaMathQA. Retained GSM8K exact-match gain, 3 seeds.');
s=slide('The corpus ordering changes with the model', 'I · RECEIVER DEPENDENCE',75,`A natural alternative is that every dataset has an intrinsic adapter cost. To test that, I compare the same five corpora on Mistral and Qwen with the same rank, example count, epochs, and codec. Each value averages three independent adapters, and all 30 curves bracket the retention threshold. Instruction is cheaper than math on Mistral, but more expensive on Qwen. Summarization also changes its position. Dialogue remains costly on both. The conclusion is specific: for these two frozen receivers and this protocol, corpus identity alone does not determine rate. Bits per adapter value normalize storage by the original adapter size; they do not assert identical whole-file size across models.`, 'Report §3.7, table labelled tab:model-corpus-rate.');
chart(s,['Instruction','Summary','Math','Code','Dialogue'],[{name:'Mistral-7B',values:[.643,.652,.737,.891,.913]},{name:'Qwen2.5-7B',values:[.774,.388,.411,.668,1.176]}],{max:1.35,format:'0.000',y:205,h:365});note(s,'R*(0.90), bits per original adapter value. Mean over 3 seeds per corpus and model.');
s=slide('Correction spectra are a promising predictor', 'I · CURRENT HYPOTHESIS',80,`This suggests looking at what a dataset asks a particular model to change. At the output head, a token gradient factorizes into a hidden representation and the prediction error vector p minus the one-hot target. We project these factors and compute a second-moment matrix. The log determinant grows when corrections are large and spread across independent directions. Across 22 distinct model–dataset conditions and seven task families, its within-model rank correlation is 0.764. Leaving one family out gives RMSE 0.187, compared with 0.264 for a model-only fit. Effective rank has slightly better held-out RMSE, so no single statistic wins every criterion. These measures were screened on the same campaign. The permutation correction handles that selection, but only new prospective data can test generality.`, 'Report §3.7, equations for g_it and I_corr, table tab:relative-info-screen.');
equation(s,'corr_gradient',64,212,750,93,'Projected token-gradient second moment');equation(s,'corr_volume',64,356,760,100,'Correction log-volume equals the sum of log one plus eigenvalues');text(s,'Large corrections across many directions',64,481,755,54,26,C.muted);text(s,'0.764',866,212,340,95,68,C.ink,true);text(s,'Within-model Spearman ρ',866,304,345,66,25);text(s,'22 conditions\n7 task families\n2 frozen 7B models',866,412,340,121,26);note(s,'Projected output-head gradients. Strongest within-model ordering in this screen; prospective validation remains open.');
s=slide('Different objectives select different boundaries', 'II · REASONING TRAJECTORIES',80,`The starting hypothesis was that reasoning might have one compact sequence of meaningful internal updates. I test four objectives on the same token gaps: movement toward the answer, verified symbolic updates, correctness-probe changes, and local PCA geometry. Each method gets the same number of boundaries. Random utility is zero and the objective-specific oracle is one. Supervised detectors recover their own targets well, as the chart shows for SmolLM. Yet oracle boundary overlap is low, and the best worst-objective utility among the tested rules is only 0.020. Qwen replicates the qualitative result. The warranted conclusion is that these tested objectives favor different partitions, not a theorem that no universal partition could exist.`, 'Report §4.3. Primary corpus: 310,044 SmolLM3-3B tokens. Replication: 61,691 Qwen3-14B tokens.');
chart(s,['Answer','Symbolic update','Correctness','PCA geometry'],[{name:'Own-objective detector AUC',values:[.999,.984,.849,.868],color:C.amber}],{x:64,y:206,w:740,h:337,max:1.1,format:'0.000',legend:false});text(s,'0.098–0.210',847,214,360,70,44,C.amber,true);text(s,'Pairwise oracle-boundary F1\nwithin ±4 tokens',847,293,365,90,26);text(s,'0.020',847,413,360,66,48,C.ink,true);text(s,'Best worst-objective utility\namong tested rules',847,486,365,83,24);note(s,'SmolLM3-3B. Equal boundary budgets. Random utility = 0, target oracle = 1.');
s=slide('An explicit handoff restores composition', 'II · A CAUSAL STATE TEST',80,`The next test has a known state space: eight states reached by a short synthetic program, followed by a pointer lookup. Frozen Qwen2.5-32B can read a supplied state and apply a local update perfectly. At horizon two it infers the endpoint about 77 percent of the time. But asking for both endpoint inference and the final lookup in one prompt gives only 13.44 percent accuracy. Instead, I ask it to predict the endpoint, remove the original history, and give the predicted state to a fresh call. Accuracy returns to 76.98 percent, matching state inference. A correct supplied endpoint gives 100 percent. The intervention supports a routing or composition failure in this assay. It does not establish a patchable native hidden-state code.`, 'Report §4.6, Native language-model state and explicit handoff.');
text(s,'Eight-state program, followed by a state-to-answer lookup',64,166,1152,34,22,C.muted);chart(s,['One-pass lookup','Predicted-state handoff','Correct-state handoff'],[{name:'Final-answer accuracy',values:[.1344,.7698,1],color:C.amber}],{x:64,y:208,w:1120,h:342,max:1.12,format:'0.00%',legend:false});callout(s,'The fresh call receives the state after the history is deleted.',559,C.amber);note(s,'Frozen Qwen2.5-32B, horizon 2, 8 states. Chance = 12.5%. Endpoint inference = 76.98%.');
s=slide('Capacity and stable names matter separately', 'II · CONTROLLED PROOF STATES',85,`I then train explicit interfaces on a finite proof task. Four facts define 16 possible ledgers, so exact state identification needs four bits under full support. At each step only the current code survives into the next call. Three bits force a collision. A canonical four-bit code assigns one fixed name to each state. A padded five-bit code keeps that naming and adds capacity. A path-aliased five-bit code gives the same semantic state two names depending on its history. Canonical and padded codes recover all states and remain exact over the tested horizon of 256. The aliased code drops to 30 to 40 percent after three active deductions. Equal bit count therefore does not imply equally usable names. Final-answer accuracy is a separate measure: 97.22 percent for canonical versus 72.22 percent one-pass.`, 'Report §4.7, Rate, shared meaning, and closure. Three training seeds.');
table(s,[['Code','Bits','Naming','Exact state'],['Lossy','3','Collisions required','Cannot recover all 16'],['Canonical','4','One name per state','100% through H = 256'],['Padded','5','Same stable naming','100% through H = 256'],['Path-aliased','5','Name depends on path','30–40% at depth 3']],64,208,1152,310,[230,95,357,470]);callout(s,'At five bits, naming changes state recovery.',554,C.amber);note(s,'16 proof states, matched training data and compute, 3 seeds. H is total horizon; depth counts active deductions.');
s=slide('Local errors accumulate under repeated use', 'II · LIMIT OF THE INTERFACE',60,`The proof rule is very regular. On a mixed register task with addition, XOR, swap, and conditional updates, the interface becomes much less reliable. A local update is correct about 89 percent of the time, evaluated from the actual supplied state. This avoids unfairly marking a later update wrong just because a previous update already failed. Even so, the final horizon-32 answer is correct only 7.92 percent of the time, close to the 6.25 percent chance rate. The illustrative calculation of 0.89 to the power 31 is about 2.7 percent, but it assumes independent errors and is not a fitted prediction of final accuracy: errors can be dependent or cancel. The important measurement is the complete self-fed execution.`, 'Report §4.7 and media/reasoning/plots/06_local_global_reliability.pdf. The 0.89^31 illustration is calculated, not experimental.');
text(s,'≈ 89%',64,219,500,112,88,C.amber,true);text(s,'Correct local transitions',64,338,500,56,30);text(s,'7.92%',700,219,515,112,88,C.ink,true);text(s,'Correct final answers at H = 32',700,338,515,76,30);equation(s,'recurrence',145,424,990,74,'Predicted states are fed into the next update before final readout');text(s,'Chance: 6.25%       One-pass reasoning: 5.83%',64,512,1152,40,25,C.muted);callout(s,'Reliable single steps do not ensure reliable long executions.',558,C.amber);
s=slide('Reasoning and answer rates also reverse', 'SYNTHESIS · ONE COMPLETED COMPARISON',70,`This is the most direct completed connection between the tracks. On MetaMathQA I use the same adapter compression protocol, but score the reasoning and final-answer spans separately. For Mistral, preserving reasoning gain at 90 percent costs about 1.070 bits per value, compared with 0.578 for answer gain. For Qwen, reasoning costs 0.471 and answers 0.575. The ordering reverses. These are update-storage rates for span-specific next-token behavior. They are not the token length of a reasoning trace, nor a measurement of the information needed by reinforcement learning. This study uses one corpus, two models, and a lexical span boundary, with fewer answer tokens. It supports model and utility dependence within that scope.`, 'Report §5.1–5.3. Rates are 1.070/0.578 on Mistral and 0.471/0.575 on Qwen for reasoning/answer.');
chart(s,['Mistral-7B','Qwen2.5-7B'],[{name:'Reasoning-span gain',values:[1.070,.471],color:C.teal},{name:'Answer-span gain',values:[.578,.575],color:C.amber}],{x:64,y:211,w:1120,h:354,max:1.25,format:'0.000'});note(s,'R*(0.90), bits per adapter value. MetaMathQA. This measures storage for retained next-token gain.');
s=slide('What the experiments establish', 'SYNTHESIS',55,`I would separate the findings from the interpretation. The adapter protocol gives an actual reloadable rate under a defined utility, and the cross-model comparisons reject dataset-only cost in the tested setting. The reasoning experiments find different useful partitions, then separate state inference from state use. Controlled interfaces show that enough capacity and stable names help, but recursive transition errors remain decisive. These observations support a common interpretation: useful information is relative to a receiver and a task, with an additional update requirement under repeated use. They do not yet reduce to a single quantity that predicts both adapter rate and reasoning reliability.`, 'Report §3.8, §4.8, §5.2–5.3.');
label(s,'Fine-tuning',64,220);text(s,'A measured file rate\nfor a stated retained behavior',64,276,550,116,35,C.ink,true);text(s,'The receiver changes the cost.',64,431,550,69,30,C.teal);label(s,'Reasoning',700,220,440,C.amber);text(s,'A state must support\nits intended next computation',700,276,510,116,35,C.ink,true);text(s,'Repeated use adds an update requirement.',700,431,510,86,30,C.amber);callout(s,'A common interpretation; a predictive law remains open.');
s=slide('The next tests must make new predictions', 'PERSPECTIVES',45,`The strongest next test is prospective. Before fine-tuning a new receiver and task, compute correction spectra separately for reasoning and answer tokens and freeze a prediction of their later rate thresholds. Then test the prediction after training. A second experiment takes one fixed reasoning adapter down the rate ladder and measures whether state decoding, state handoff, and answer behavior fail together. Different failure points would show different information requirements within one model; coincident failure could reveal a stronger common constraint. These are proposed experiments in the report, not completed results.`, 'Report §5.4, How to test the bridge.');
text(s,'01',64,210,110,70,48,C.teal,true);text(s,'Predict before training',200,213,990,55,36,C.ink,true);text(s,'Use span-specific correction spectra on new models and tasks.\nFreeze predictions of R* before observing the adapter rates.',200,286,985,105,29);rule(s,64,416,1152);text(s,'02',64,460,110,70,48,C.amber,true);text(s,'Follow state use along the rate ladder',200,463,990,55,36,C.ink,true);text(s,'Measure decoding, handoff, and answer behavior\nwhile compressing the same reasoning adapter.',200,535,985,96,29);
s=slide('Useful information depends on its use', 'CONCLUSION',25,`The main contribution is to replace loose information proxies with concrete behavioral tests. For fine-tuning, I measure a reloadable update at a chosen retention threshold. For reasoning, I distinguish visible or decodable structure from a state that supports continued computation. The strongest shared lesson is dependence on receiver and task, with update reliability becoming essential under recursion. Correction spectra provide a promising way to turn that interpretation into a prediction, but that remains the next research step. Thank you.`, 'Report abstract, §5 and §6.',true);
text(s,'Receiver',64,225,1120,76,55,'#78C8BE',true);text(s,'Which model must use the information?',64,305,1110,58,32,C.white);text(s,'Task and update rule',64,416,1120,76,55,'#E4AA79',true);text(s,'Which behavior must survive, and for how long?',64,497,1110,65,32,C.white);
// Backup slides.
s=slide('Equal snapshot information, unequal memory', 'BACKUP · EXACT FINITE CONTROL',0,`This is an exact finite controller, not an LLM experiment. Across 90 cells the full public history and a 12-bit suffix initially have the same support, state mutual information of 2.512 bits, and path leakage of 1.781 bits. Their update rules then diverge: the suffix discards older evidence. At horizon 32 their regrets are 2.20 and 30.91. Across cells, pooled suffix regret is 7.19 times larger. A 12-bit explicit field state removes 79.3 percent of no-memory regret, compared with 93.7 percent for full history and 54.8 percent for the suffix. The field state can still miss a held-out goal if its objective omitted needed fields.`, 'Report §4.5, Exact control: snapshot information is not memory.');
chart(s,['Full history','12-bit text suffix'],[{name:'Regret at horizon 32',values:[2.20,30.91],color:C.amber}],{x:64,y:211,w:720,h:344,max:35,format:'0.00',legend:false});text(s,'Same initial information',836,229,380,70,31,C.ink,true);text(s,'I(state; memory) = 2.512 bits\nPath leakage = 1.781 bits',836,335,380,118,26);note(s,'Exact finite control, 90 task cells. Regret is lower-is-better. This is separate from the LLM assays.');
s=slide('Distinct examples at fixed training exposure', 'BACKUP · DIVERSITY',0,`The distinct-example sweep uses 2,000 optimizer steps and 32,000 example presentations in every condition. The mean rate generally rises with distinct records but is not monotone. Each point has three seeds. The fit over 15 runs has R squared 0.78, but it is a within-campaign trend, not a general scaling law. The separate content-diversity control fixes 8,000 examples and increases the number of source problems, moving mean rate from 0.682 to 0.742 over six seeds. SQL replication is weak and inconsistent, whereas XBRL increases in all six model-seed pairs, with a support-coverage confound.`, 'Report §3.5 and Appendix table tab:distinct-rate.');
chart(s,['2,000','4,000','8,000','16,000','32,000'],[{name:'Mean R*(0.90)',values:[.645,.740,.709,.832,1.002],color:C.teal}],{max:1.2,format:'0.000',y:215,h:350});note(s,'Distinct training examples. 2,000 optimizer steps and 32,000 presentations fixed. 3 seeds per condition.');
s=slide('What the codec and threshold count', 'BACKUP · MEASUREMENT CONTRACT',0,`The file includes quantized factors, scales, metadata, bit packing and zlib compression. At one bit and above, matrix rows use scalar quantization, with a sign and row-scale code at one bit. Below one bit per original adapter value, paired A/B rank directions can be dropped. The normalization remains the original adapter size. The base model is shared and excluded from the file budget. R* is a minimum over the tested codec ladder, so it is an attainable measured rate rather than a globally optimal description length. A rank change also changes the carrier; whole-file size and per-value rate should both be inspected when comparing architectures.`, 'Report §3.3, Appendix Codec ladder and Adapter carrier and location controls.');
label(s,'Included in the file',64,219);text(s,'Quantized factors\nScales and metadata\nBit-packed, zlib-compressed payload',64,281,540,190,31);label(s,'Conditioned on',700,219,510);text(s,'A shared frozen backbone\nOne fixed adapter checkpoint\nA named held-out utility',700,281,510,190,31);callout(s,'R* is an attainable rate within the tested codec family.');note(s,'Sub-bit rates use paired rank-direction removal. File rate uses the original adapter value count.');
s=slide('Prediction, accuracy, and state recovery', 'BACKUP · METRIC DEFINITIONS',0,`These metrics answer different questions and should not be substituted for one another. NLL uses a proper probabilistic score at every scored token, while exact match checks a final task answer. Retained gain normalizes either kind of behavior relative to a frozen baseline and raw adapter, so the underlying utility must always be stated. Exact state tests whether the entire finite ledger is correct. Boundary AUC measures ranking of labeled token gaps, whereas boundary F1 measures agreement of selected points. In particular, high AUC does not imply a boundary set useful for another objective, and 90 percent NLL-gain retention is not 90 percent answer accuracy.`, 'Report §2.7, §3.3, §4.3, §4.7.');
table(s,[['Metric','Question'],['Held-out NLL','Does the model predict the scored tokens?'],['Retained gain','How much improvement over the base survives?'],['Answer exact match','Is the final task answer correct?'],['Exact state','Does the complete supplied ledger match?'],['Boundary AUC / F1','Can we detect a target / do selected gaps agree?']],64,211,1152,352,[355,797]);note(s,'Every reported rate and retention value needs a named utility and evaluation span.');
s=slide('Semantic boundaries are decodable too', 'BACKUP · JUDGED REASONING SPANS',0,`A larger model judges nine edit types in concise correct SmolLM traces. After alignment and filtering, the analysis retains 1,761 spans across 58 traces. The latent detector reaches AUC 0.982 under a question-disjoint split, and 0.969 away from sentence endings. However, lexical TF–IDF reaches 0.892, so the result is not uniquely latent. Their transfer utilities to the four operational targets are minus 0.012, 0.043, 0.036, and 0.324. This supports the presence of learnable semantic structure, with limited cross-objective transfer. It does not establish a unique decomposition, and the judge labels are not a human gold standard.`, 'Report §4.4, Judged semantic spans.');
chart(s,['Latent detector','Away from sentence ends','Lexical TF–IDF'],[{name:'Held-out boundary AUC',values:[.982,.969,.892],color:C.amber}],{max:1.1,format:'0.000',legend:false,y:212,h:338});note(s,'1,761 judge-labeled spans, 58 traces. Question-disjoint evaluation. Labels come from Qwen-110B-A25B.');
s=slide('Correction-spectrum screen and its limits', 'BACKUP · PREDICTOR COMPARISON',0,`The comparison removes exact data reuses and averages training seeds, leaving 22 distinct model–dataset conditions from seven families. Ten measures were screened. The adjusted permutation p value accounts for choosing the strongest candidate within that screen. RMSE leaves out one task family at a time, which is more informative than a pooled in-sample correlation, but still shares the same two model families and development campaign. The factors come from projected output-head gradients, not the full adapter Fisher. Effective rank has the lowest held-out RMSE here, and log volume has the strongest within-model ordering. The next step is to fix the measure and test unseen conditions prospectively.`, 'Report §3.7, table tab:relative-info-screen.');
table(s,[['Measure','Within-model ρ','Adjusted p','Held-out RMSE'],['Correction log-volume','0.764','0.00034','0.187'],['Correction effective rank','0.609','0.0112','0.181'],['Surprise-weighted log-volume','0.614','0.0103','0.204'],['Base target code length','0.200','0.524','0.261'],['Model-only fit','—','—','0.264']],64,210,1152,344,[474,236,202,240]);note(s,'RMSE in bits per adapter value, lower is better. Family-held-out evaluation. 22 conditions, 10 screened measures.');
await fs.writeFile(path.join(ROOT,'.build','speaker-notes.json'),JSON.stringify(script,null,2));
await fs.writeFile(path.join(ROOT,'.build','presentation.json'),JSON.stringify(p.toProto()));
const candidate=path.join(ROOT,'.build','candidate.pptx');
await (await PresentationFile.exportPptx(p)).save(candidate);
console.log('Exported',index,'slides; main timing',script.reduce((a,x)=>a+x.seconds,0),'seconds');
for(let i=0;i<p.slides.items.length;i++){const preview=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(path.join(ROOT,'.build',`slide-${i+1}.png`),new Uint8Array(await preview.arrayBuffer()));console.log('Rendered',i+1);}
const result=await finalizePresentation({workspaceDir:ROOT,candidatePath:candidate,finalPath:path.join(ROOT,'output','soutenance_joey_david_v2.pptx'),pythonExecutable:PY,integrityValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit',...tableOwners.flatMap(n=>['--require-native-table-slide',String(n)])],requiredNativeChartOwnerSlides:chartOwners,requiredNativeTableOwnerSlides:tableOwners,fontPolicy:{basis:'design',families:[font]},materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:path.join(ROOT,'.build','validation-v2.json')});
console.log(JSON.stringify(result));
